@if(auth()->user()?->is_admin == 1)
<section class="review-board mt-4" id="attendanceReviewBoard">
    <div class="review-heading">
        <div><span class="review-kicker">LIVE LOCATION CONTROL</span><h5>Attendance Review Desk</h5></div>
        <div class="review-counts"><span class="review-pill amber"><b id="reviewCount">0</b> In review</span><span class="review-pill red"><b id="suspiciousCount">0</b> Suspicious</span></div>
    </div>
    <div id="reviewCards" class="review-grid"><div class="review-empty">Checking live attendance reviews...</div></div>
</section>
<div class="modal fade" id="reviewDetailModal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title">Attendance Investigation</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body" id="reviewDetailBody"></div></div></div></div>
<style>
.review-board{background:#fff;border:1px solid #dfe5ec;border-top:4px solid #334155;border-radius:8px;padding:18px}.review-heading{display:flex;align-items:center;justify-content:space-between;gap:16px}.review-heading h5{margin:2px 0 0;color:#172b4d}.review-kicker{font-size:10px;font-weight:800;letter-spacing:1.2px;color:#64748b}.review-counts{display:flex;gap:8px}.review-pill{padding:6px 10px;border-radius:4px;font-size:12px;font-weight:700}.review-pill.amber{background:#fff7ed;color:#9a3412}.review-pill.red{background:#fef2f2;color:#b91c1c}.review-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:12px;margin-top:14px}.review-card{border:1px solid #e2e8f0;border-left:5px solid #f59e0b;border-radius:6px;padding:14px;background:#fff}.review-card.suspicious{border-left-color:#dc2626}.review-card-top{display:flex;justify-content:space-between;gap:10px}.review-name{font-weight:800;color:#1e293b}.review-code,.review-info{font-size:12px;color:#64748b}.review-timer{font:800 18px monospace;color:#b45309}.review-card.suspicious .review-timer{color:#dc2626}.review-distance{font-size:13px;margin:12px 0}.review-actions{display:flex;gap:7px}.review-empty{padding:28px;text-align:center;color:#64748b;grid-column:1/-1}@media(max-width:650px){.review-heading{align-items:flex-start;flex-direction:column}.review-counts{width:100%}.review-pill{flex:1;text-align:center}}
</style>
<script>
(function(){
let reviewItems=[];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const seconds=d=>d?Math.max(0,Math.floor((new Date(d).getTime()-Date.now())/1000)):0;
const clock=s=>String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');
function render(){const box=document.getElementById('reviewCards');document.getElementById('reviewCount').textContent=reviewItems.filter(x=>x.status==='in_review').length;document.getElementById('suspiciousCount').textContent=reviewItems.filter(x=>x.status==='suspicious').length;if(!reviewItems.length){box.innerHTML='<div class="review-empty"><i class="fas fa-check-circle text-success mr-1"></i>No attendance needs review.</div>';return}box.innerHTML=reviewItems.map(x=>`<article class="review-card ${x.status}"><div class="review-card-top"><div><div class="review-name">${esc(x.employee)}</div><div class="review-code">${esc(x.employee_code||x.office||'')}</div></div><div class="review-timer" data-deadline="${esc(x.deadline)}">${x.status==='suspicious'?'FLAGGED':clock(seconds(x.deadline))}</div></div><div class="review-distance"><i class="fas fa-route mr-1"></i>${x.distance===null?'Outside area':Math.round(x.distance)+' m from office'} ${x.radius?'(allowed '+x.radius+' m)':''}</div><div class="review-info">${esc(x.reason||'Outside configured office area')}</div><div class="review-actions mt-3"><button class="btn btn-sm btn-outline-dark" onclick="window.showAttendanceReview(${x.id})"><i class="fas fa-search mr-1"></i>Details</button><button class="btn btn-sm btn-success" onclick="window.setAttendanceReview(${x.id},'present')"><i class="fas fa-check mr-1"></i>Approve</button></div></article>`).join('')}
async function load(){try{const r=await fetch('{{ route('admin.attendance-reviews.feed') }}',{headers:{Accept:'application/json'}});const d=await r.json();reviewItems=d.items||[];render()}catch(e){document.getElementById('reviewCards').innerHTML='<div class="review-empty">Review feed could not be loaded.</div>'}}
window.showAttendanceReview=id=>{const x=reviewItems.find(i=>i.id===id);if(!x)return;document.getElementById('reviewDetailBody').innerHTML=`<div class="row"><div class="col-md-6"><b>Employee</b><p>${esc(x.employee)} (${esc(x.employee_code)})</p><b>Punch time</b><p>${esc(x.punch_time)}</p><b>Punch location</b><p>${esc(x.punch_location||'Address unavailable')}</p></div><div class="col-md-6"><b>Office area</b><p>${esc(x.area||'Nearest area')} - ${esc(x.radius)} m</p><b>Punch distance</b><p>${esc(x.distance)} m</p><b>Reached office area</b><p>${esc(x.entered_at||'Not reached before deadline')}</p><a class="btn btn-sm btn-outline-primary" target="_blank" href="https://www.google.com/maps?q=${encodeURIComponent(x.punch_latitude+','+x.punch_longitude)}"><i class="fas fa-map-marker-alt mr-1"></i>Open punch location</a></div></div><hr><div class="form-group"><label>Admin note</label><textarea id="reviewAdminNote" class="form-control" rows="2">${esc(x.reason||'')}</textarea></div><button class="btn btn-success mr-2" onclick="window.setAttendanceReview(${x.id},'present')">Mark Present</button><button class="btn btn-warning mr-2" onclick="window.setAttendanceReview(${x.id},'half_time')">Mark Half Day</button><button class="btn btn-danger" onclick="window.setAttendanceReview(${x.id},'suspicious')">Keep Suspicious</button>`;$('#reviewDetailModal').modal('show')};
window.setAttendanceReview=async(id,status)=>{const note=document.getElementById('reviewAdminNote')?.value||'';const url='{{ route('admin.attendance-reviews.update', '__ID__') }}'.replace('__ID__',id);const r=await fetch(url,{method:'PATCH',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':'{{ csrf_token() }}'},body:JSON.stringify({status,review_note:note})});if(r.ok){$('#reviewDetailModal').modal('hide');load()}};
setInterval(()=>document.querySelectorAll('[data-deadline]').forEach(el=>{if(el.textContent!=='FLAGGED')el.textContent=clock(seconds(el.dataset.deadline))}),1000);setInterval(load,15000);load();
})();
</script>
@endif
