<div class="container">

    {{-- Payroll Summary --}}
    <h5>Payroll Summary</h5>
    <div class="row">
        @php
            $payrollData = [
                'Employee' => 'Name - ' . ($payroll->employee->full_name ?? '-'),
                'Month/Year' => 'Month - ' . DateTime::createFromFormat('!m', $payroll->month)->format('F') . ' ' . $payroll->year,
                'Working Days' => 'Working Days - ' . $payroll->working_days,
                'Present Days' => 'Present Days - ' . $payroll->present_days,
                'Paid Leaves' => 'Paid Leaves - ' . $payroll->paid_leaves,
                'Half Days' => 'Half Days - ' . $payroll->half_days,
                'Basic' => 'Basic - ₹' . number_format($payroll->basic, 2),
                'HRA' => 'HRA - ₹' . number_format($payroll->hra, 2),
                'Allowance' => 'Allowance - ₹' . number_format($payroll->allowance, 2),
                'Bonus' => 'Bonus - ₹' . number_format($payroll->bonus, 2),
                'Gross Salary' => 'Gross - ₹' . number_format($payroll->gross_salary, 2),
                'Deductions' => 'Deductions - ₹' . number_format($payroll->deductions, 2),
                'Manual Adjustment' => 'Adjustment - ₹' . number_format($payroll->manual_adjustment, 2),
                'Net Salary' => 'Net - ₹' . number_format($payroll->net_salary, 2),
                'Remaining Salary' => 'Remaining - ₹' . number_format($payroll->remaining_salary, 2),
                'Status' => 'Status - ' . $payroll->status,
                'Remarks' => 'Remarks - ' . ($payroll->remarks ?? '-'),
                'Salary Generated By' => 'Generated By - ' . ($payroll->generatedBy->name ?? '-'),
                'Generated At' => 'Generated At - ' . $payroll->generated_at,
                'Branch' => 'Branch - ' . ($payroll->branch->name ?? '-'),
            ];
            @endphp


        @foreach(array_chunk($payrollData, ceil(count($payrollData)/3)) as $chunk)
            <div class="col-md-4">
                <table class="table table-sm table-bordered">
                    @foreach($chunk as $label => $value)
                        <tr>
                            <th>{{ $label }}</th>
                            <td>{{ $value }}</td>
                        </tr>
                    @endforeach
                </table>
            </div>
        @endforeach
    </div>

    {{-- Adjustments --}}
    <h5 class="mt-4">Adjustments</h5>
    @if($adjustments->count())
        <ul class="list-group">
            @foreach($adjustments as $adj)
                <li class="list-group-item">
                    <strong>{{ ucfirst($adj->type) }}</strong> - ₹{{ number_format($adj->amount, 2) }}
                    <br><small class="text-muted">{{ $adj->reason }}</small>
                </li>
            @endforeach
        </ul>
    @else
        <p class="text-muted">No adjustments found.</p>
    @endif

    {{-- Attendance Summary --}}
    <h5 class="mt-4">Attendance Summary</h5>
    @php
        // Fetch attendance using employee_id instead of user_id
        $attendance = \App\Models\AttendanceDetail::where('user_id', $payroll->employee->user_id)
                        ->whereMonth('date', $payroll->month)
                        ->whereYear('date', $payroll->year)
                        ->orderBy('date')
                        ->get();
    @endphp

    @if($attendance->count())
        <table class="table table-sm table-striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Status</th>
                    <th>Punch In</th>
                    <th>Punch In Location</th>
                    <th>Punch Out</th>
                    <th>Punch Out Location</th>
                    <th>Hours Worked</th>
                </tr>
            </thead>
            <tbody>
                @foreach($attendance as $att)
                    @php
                        $punchIn = $att->punch_in_time ? \Carbon\Carbon::parse($att->punch_in_time) : null;
                        $punchOut = $att->punch_out_time ? \Carbon\Carbon::parse($att->punch_out_time) : null;
                        $hoursWorked = $punchIn && $punchOut ? $punchOut->diffInHours($punchIn) . 'h ' . $punchOut->diffInMinutes($punchIn) % 60 . 'm' : '-';
                    @endphp
                    <tr>
                        <td>{{ $att->date }}</td>
                        <td>{{ \App\Models\AttendanceDetail::STATUS_SELECT[$att->status] ?? $att->status }}</td>
                        <td>{{ $att->punch_in_time ?? '-' }}</td>
                        <td>{{ $att->punch_in_location ?? '-' }}</td>
                        <td>{{ $att->punch_out_time ?? '-' }}</td>
                        <td>{{ $att->punch_out_location ?? '-' }}</td>
                        <td>{{ $hoursWorked }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <p class="text-muted">No attendance records for this month.</p>
    @endif

</div>
