@extends('layouts.admin')

@section('content')
<div class="card shadow-lg border-0">
    <div class="card-header bg-gradient-primary text-white d-flex justify-content-between align-items-center">
        <h5 class="mb-0">Payroll List - {{ DateTime::createFromFormat('!m', $month)->format('F') }} {{ $year }}</h5>

        <form method="GET" action="{{ route('admin.payroll.list') }}" class="form-inline">
            <select name="month" class="form-control form-control-sm mr-2" required>
                @for($m=1; $m<=12; $m++)
                    <option value="{{ $m }}" {{ $m == $month ? 'selected' : '' }}>
                        {{ DateTime::createFromFormat('!m', $m)->format('F') }}
                    </option>
                @endfor
            </select>
            <select name="year" class="form-control form-control-sm mr-2" required>
                @for($y = date('Y') - 5; $y <= date('Y') + 1; $y++)
                    <option value="{{ $y }}" {{ $y == $year ? 'selected' : '' }}>{{ $y }}</option>
                @endfor
            </select>
            <button type="submit" class="btn btn-sm btn-light shadow-sm">Filter</button>
        </form>
    </div>

    <!-- Payroll Details Modal -->
    <div class="modal fade" id="payrollDetailsModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-scrollable">
            <div class="modal-content shadow-lg">
                <div class="modal-header bg-primary text-white">
                    <h5 class="modal-title">Payroll Details</h5>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
                </div>
                <div class="modal-body" id="payrollDetailsBody">
                    <div class="text-center p-5">
                        <i class="fas fa-spinner fa-spin fa-2x"></i><br>
                        Loading details...
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    <div class="card-body table-responsive">

        <!-- 💰 Total Net Salary Display -->
        <div class="mb-3 text-end">
            <h5 class="fw-bold">
                💰 Total Net Salary: <span id="totalNetSalary" class="text-success">₹0.00</span>
            </h5>
        </div>

        <table id="payrollTable" class="table table-hover table-striped table-bordered align-middle text-center" style="width:100%">
            <thead class="bg-dark text-white">
                <tr>
                    <th>#</th>
                    <th>Employee</th>
                    <th>Present</th>
                    <th>Half Days</th>
                    <th>Paid Leaves</th>
                    <th>Unpaid Leaves</th>
                    <th>Absent</th>
                    <th>Holidays</th>
                    <th>Final Paid Days</th>
                    <th>Working Days</th>
                    <th>Basic</th>
                    <th>HRA</th>
                    <th>Allowance</th>
                    <th>Bonus</th>
                    <th>Gross Salary</th>
                    <th>Deductions</th>
                    <th>Adjustment</th>
                    <th>Net Salary</th>
                    <th>Manual Adjustment</th>
                    <th>Generated By</th>
                    <th>Message</th>
                    <th>Generated At</th>
                    <th>Status</th>
                    <th>Remarks</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @forelse($payrolls as $payroll)
                    <tr>
                        <td>{{ $loop->iteration }}</td>
                        <td>
                            <strong>{{ $payroll->employee->full_name ?? '-' }}</strong><br>
                            <small class="text-muted">({{ $payroll->employee->employee_code ?? '-' }})</small>
                        </td>
                        <td>{{ $payroll->present_days }}</td>
                        <td>{{ $payroll->half_days ?? '0' }}</td>
                        <td>{{ $payroll->paid_leaves ?? '0' }}</td>
                        <td>{{ $payroll->unpaid_leaves ?? '0' }}</td>
                        <td>{{ $payroll->absent_days ?? '0' }}</td>
                        <td>{{ $payroll->holidays ?? '0' }}</td>
                        <td>{{ $payroll->final_paid_days ?? '-' }}</td>
                        <td>{{ $payroll->total_days }}</td>
                        <td>₹{{ number_format($payroll->employee->basic_salary, 2) }}</td>
                        <td>₹{{ number_format($payroll->employee->hra, 2) }}</td>
                        <td>₹{{ number_format($payroll->employee->other_allowances, 2) }}</td>
                        <td>₹{{ number_format($payroll->employee->bonus, 2) }}</td>
                        <td>₹{{ number_format($payroll->employee->net_salary ?? ($payroll->employee->basic + $payroll->employee->hra + $payroll->employee->allowance + $payroll->employee->bonus), 2) }}</td>
                        <td>₹{{ number_format($payroll->employee->deductions, 2) }}</td>
                        <td>₹{{ number_format($payroll->manual_adjustment ?? 0, 2) }}</td>

                        <!-- ✅ Net Salary Logic -->
                        <td>
                            @if(!empty($payroll->manual_adjustment) && isset($payroll->remaining_salary))
                                <strong class="text-warning net-salary">
                                    {{ $payroll->remaining_salary }}
                                </strong>
                            @else
                                <strong class="{{ $payroll->remaining_salary ? 'text-warning' : 'text-success' }} net-salary">
                                    {{ $payroll->remaining_salary ?? $payroll->net_salary }}
                                </strong>
                            @endif
                        </td>

                        <td>{{ $payroll->manual_adjustment ?? 'N/A' }}</td>
                        <td>{{ $payroll->salary_generated_role ?? 'N/A' }}</td>
                        <td>{{ $payroll->message ?? 'N/A' }}</td>
                        <td>{{ $payroll->generated_at ?? 'N/A' }}</td>
                        <td>
                            <span class="badge badge-{{ $payroll->status == 'Paid' ? 'success' : 'warning' }}">
                                {{ $payroll->status }}
                            </span>
                        </td>
                        <td>{{ $payroll->remarks ?? '-' }}</td>
                        <td>
                            <a href="{{ route('admin.payrolls.manualAdjustForm', $payroll->id) }}" class="btn btn-sm btn-info">
                                <i class="fas fa-sliders-h"></i>
                            </a>
                            <a href="{{ route('admin.payrolls.download', $payroll->id) }}" class="btn btn-sm btn-danger">
                                <i class="fas fa-file-pdf"></i>
                            </a>
                            <a href="{{ route('admin.payrolls.manualAdjustForm', $payroll->id) }}" class="btn btn-sm btn-primary">
                                <i class="fas fa-eye"></i>
                            </a>
                            <a href="javascript:void(0)" 
                               class="btn btn-sm btn-warning viewPayrollDetails" 
                               data-id="{{ $payroll->id }}">
                               <i class="fas fa-info-circle"></i>
                            </a>
                            <button type="button" class="btn btn-sm btn-outline-warning viewPartPayments" data-id="{{ $payroll->id }}">
                                <img src="{{ asset('200.gif') }}" alt="" width="30"> 
                            </button>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="23" class="text-center text-muted">No payroll data found for this month.</td>
                    </tr>
                @endforelse
            </tbody>
        </table>

        <!-- Part Payment Modal -->
        <div class="modal fade" id="partPaymentModal" tabindex="-1" aria-hidden="true">
            <div class="modal-dialog modal-lg modal-dialog-scrollable">
                <div class="modal-content">
                    <div class="modal-header bg-warning text-dark">
                        <h5 class="modal-title">💳 Part Payment History</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                    </div>
                    <div class="modal-body" id="partPaymentModalBody">
                        <div class="text-center p-4">
                            <i class="fas fa-spinner fa-spin fa-2x"></i><br> Loading...
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
@endsection

@section('scripts')
<!-- Bootstrap Bundle -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

<!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>

<!-- DataTables -->
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.4.1/css/buttons.bootstrap5.min.css">
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.bootstrap5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.colVis.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.html5.min.js"></script>
<script src="https://cdn.datatables.net/buttons/2.4.1/js/buttons.print.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>

<script>
$(document).on('click', '.viewPayrollDetails', function () {
    let payrollId = $(this).data('id');
    var modal = new bootstrap.Modal(document.getElementById('payrollDetailsModal'));
    modal.show();

    $('#payrollDetailsBody').html(`
        <div class="text-center p-5">
          <i class="fas fa-spinner fa-spin fa-2x"></i><br>
          Fetching details...
        </div>
    `);

    $.ajax({
        url: "{{ route('admin.payrolls.details') }}",
        type: "GET",
        data: { id: payrollId },
        success: function(res) {
            $('#payrollDetailsBody').html(res.html);
        },
        error: function() {
            $('#payrollDetailsBody').html('<div class="alert alert-danger">Failed to load details.</div>');
        }
    });
});

$(document).on('click', '.viewPartPayments', function () {
    let payrollId = $(this).data('id');
    $('#partPaymentModal').modal('show');
    $('#partPaymentModalBody').html(`
        <div class="text-center p-5">
            <i class="fas fa-spinner fa-spin fa-2x"></i><br> Fetching part payments...
        </div>
    `);

    $.ajax({
        url: "{{ route('admin.payrolls.partPaymentsList') }}",
        type: "GET",
        data: { id: payrollId },
        success: function(res) {
            $('#partPaymentModalBody').html(res.html);
        },
        error: function() {
            $('#partPaymentModalBody').html('<div class="alert alert-danger">Unable to load data.</div>');
        }
    });
});

function calculateTotalNetSalary() {
    let total = 0;
    $('.net-salary').each(function() {
        let val = parseFloat($(this).text().replace(/[₹,]/g, '')) || 0;
        total += val;
    });
    $('#totalNetSalary').text('₹' + total.toLocaleString('en-IN', { minimumFractionDigits: 2 }));
}

$(document).ready(function() {
    let table = $('#payrollTable').DataTable({
        pageLength: 10,
        lengthMenu: [5, 10, 25, 50, 100, 200],
        responsive: true,
        dom: '<"d-flex justify-content-between align-items-center mb-2"Bf>rt<"d-flex justify-content-between mt-3"lip>',
        buttons: [
            { extend: 'colvis', text: '<i class="fas fa-eye"></i> Show/Hide Columns', className: 'btn btn-sm btn-outline-primary' },
            { extend: 'copy', text: '<i class="fas fa-copy"></i> Copy', className: 'btn btn-sm btn-outline-secondary' },
            { extend: 'csv', text: '<i class="fas fa-file-csv"></i> CSV', className: 'btn btn-sm btn-outline-success' },
            { extend: 'excel', text: '<i class="fas fa-file-excel"></i> Excel', className: 'btn btn-sm btn-outline-success' },
            { extend: 'pdf', text: '<i class="fas fa-file-pdf"></i> PDF', className: 'btn btn-sm btn-outline-danger' },
            { extend: 'print', text: '<i class="fas fa-print"></i> Print', className: 'btn btn-sm btn-outline-dark' }
        ]
    });

    calculateTotalNetSalary();

    table.on('draw', function() {
        calculateTotalNetSalary();
    });
});
</script>
@endsection
